version: "3.8"

services:
  node:
    container_name: node
    build: ./docker/node
    ports:
      - 8501:8080
    privileged: true
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
